# Generated by Django 4.2 on 2023-04-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.PositiveIntegerField(choices=[(1000, '1,000'), (2000, '2,000'), (3000, '3,000'), (4000, '4,000'), (5000, '5,000'), (6000, '6,000'), (7000, '7,000'), (8000, '8,000'), (9000, '9,000'), (10000, '10,000')], default='1000'),
        ),
    ]
