# Generated by Django 4.1.3 on 2022-11-28 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_remove_attendance_roll_no_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='by',
        ),
        migrations.AddField(
            model_name='notice',
            name='post_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
